#Login
url=https://automationexercise.com/
emailAddress=tikeshwarfc1@gmail.com
password=Tikeshwar@2021
browser=chrome


#Registration
#url=https://automationexercise.com/
#name=Rahul Kumar
#emailAddress=rahul22@gmail.com
#browser=chrome